# Generated by Django 3.1.4 on 2021-04-08 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_auto_20210405_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='oraganization',
            new_name='oragnization',
        ),
    ]
