# Generated by Django 3.1.4 on 2021-04-08 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_auto_20210408_0027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='oragnization',
            new_name='organization',
        ),
    ]
