# Generated by Django 3.1.4 on 2021-04-08 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_auto_20210408_0030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='oraganization',
            new_name='organization',
        ),
    ]
