# Generated by Django 3.1.4 on 2021-04-08 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_auto_20210408_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, choices=[('Converted', 'Converted'), ('Contacted', 'Contacted'), ('Unconverted', 'Unconverted')], max_length=30, null=True),
        ),
    ]
